from ..resources.get_forecasts import GetForecast
from ..resources.get_measurements import GetMeasurements
from ..resources.post_measurements import PostMeasurements
from ..resources.get_testservice import GetTestService
from ..resources.post_register_user import PostRegisterUser
from ..resources.post_register_installation import PostRegisterInstallation
from ..resources.patch_status_installation import PatchStatusInstallation
from ..resources.post_login import PostLogin
from ..resources.get_user_list import GetUserList
from ..resources.put_update_permissions import PutUpdatePermission
from ..resources.patch_reset_password import PatchResetPassword
from ..resources.get_kpi import GetKPI
from ..resources.get_installations_list import GetInstallationsInfo
